# Generated by Django 3.2.15 on 2022-09-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesModel',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=200)),
                ('dept_name', models.CharField(max_length=200)),
            ],
        ),
    ]
