version: '3'

services:
  db:
    image: mysql
    environment:
       MYSQL_DATABASE: 'testdb'
      #  MYSQL_USER: 'root'
       MYSQL_PASSWORD: ''
       MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - /opt/testdb/mysql_data:/var/lib/mysql
    ports:
      - "33070:3306"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
        - .:/code
    ports:
        - "8000:8000"
    depends_on:
      - db